/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.CarProfile;
import model.CarRecords;

/**
 *
 * @author architnigam
 */
public class ExpiredCertificateCarsPanel extends javax.swing.JPanel {

    /**
     * Creates new form ExpiredCertificateCarsPanel
     */
    CarRecords carRecords;
    public ExpiredCertificateCarsPanel(CarRecords carRecords) {
        initComponents();
        DefaultTableModel model = (DefaultTableModel) tblExpiredCars.getModel();
        model.setRowCount(0);
        
         for(CarProfile cp : carRecords.getCarRecords())
         {
             Date expiryDate = cp.getCarExpirationDate();
             Date todayDate = new Date();
             if(expiryDate.before(todayDate) )
             {
                Object[] row = new Object[7];
                row[0] =  cp.getDriverName();
                row[1] =  cp.getCarBrand() + " " + cp.getCarModelNumber();
                row[2] = cp.getCarSerialNumber();
                row[3] = cp.getAvailabilityStatus();
                row[4] = cp.getCarLoctatedInCity();
                row[5] = cp.getMaximumSeatingCapacity();
                row[6] = cp.getCarExpirationDate();
                model.addRow(row);
             }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpiredCars = new javax.swing.JTable();

        tblExpiredCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Driver Name", "Car Name", "Vehicle Number", "Availability", "Location", "Maximum Capacity", "License Certificate Date"
            }
        ));
        jScrollPane1.setViewportView(tblExpiredCars);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpiredCars;
    // End of variables declaration//GEN-END:variables
}
