/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.CarProfile;
import model.CarRecords;

/**
 *
 * @author architnigam
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    CarProfile carProfile;
    CarRecords carRecords;
    public MainJFrame() {
        initComponents();
        carProfile = new CarProfile();
        carRecords = new CarRecords();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        selectionPanel = new javax.swing.JPanel();
        btnCreateCarProfile = new javax.swing.JButton();
        btnManageBookings = new javax.swing.JButton();
        btnViewCars = new javax.swing.JButton();
        btnImportXMLData = new javax.swing.JButton();
        lblSearchBy = new javax.swing.JLabel();
        btnSearchBrand = new javax.swing.JButton();
        btnSearchAvailability = new javax.swing.JButton();
        btnSearchManufactureYear = new javax.swing.JButton();
        btnSearchSeats = new javax.swing.JButton();
        btnSearchVehicleNumber = new javax.swing.JButton();
        btnSearchModelNumber = new javax.swing.JButton();
        btnSearchCity = new javax.swing.JButton();
        btnExpiredCars = new javax.swing.JButton();
        workPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateCarProfile.setText("New Car Profile");
        btnCreateCarProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCarProfileActionPerformed(evt);
            }
        });

        btnManageBookings.setText("Manage Bookings");
        btnManageBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBookingsActionPerformed(evt);
            }
        });

        btnViewCars.setText("Car Profile Modifications");
        btnViewCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCarsActionPerformed(evt);
            }
        });

        btnImportXMLData.setText("Import Data from XML");
        btnImportXMLData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportXMLDataActionPerformed(evt);
            }
        });

        lblSearchBy.setText("Search By:");

        btnSearchBrand.setText("Brand");
        btnSearchBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBrandActionPerformed(evt);
            }
        });

        btnSearchAvailability.setText("Availability");
        btnSearchAvailability.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAvailabilityActionPerformed(evt);
            }
        });

        btnSearchManufactureYear.setText("Manufacture Year");
        btnSearchManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchManufactureYearActionPerformed(evt);
            }
        });

        btnSearchSeats.setText("Seats");
        btnSearchSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchSeatsActionPerformed(evt);
            }
        });

        btnSearchVehicleNumber.setText("Vehicle Index Number");
        btnSearchVehicleNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchVehicleNumberActionPerformed(evt);
            }
        });

        btnSearchModelNumber.setText("Model Number");
        btnSearchModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchModelNumberActionPerformed(evt);
            }
        });

        btnSearchCity.setText("City");
        btnSearchCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCityActionPerformed(evt);
            }
        });

        btnExpiredCars.setText("View Expired Licenses of Cars");
        btnExpiredCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpiredCarsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout selectionPanelLayout = new javax.swing.GroupLayout(selectionPanel);
        selectionPanel.setLayout(selectionPanelLayout);
        selectionPanelLayout.setHorizontalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateCarProfile)
                            .addComponent(btnManageBookings)
                            .addComponent(btnViewCars)
                            .addComponent(btnImportXMLData)))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblSearchBy))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchBrand))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchAvailability))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchManufactureYear))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchSeats))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSearchVehicleNumber))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(selectionPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSearchCity))
                            .addComponent(btnSearchModelNumber)))
                    .addGroup(selectionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExpiredCars)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        selectionPanelLayout.setVerticalGroup(
            selectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selectionPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnCreateCarProfile)
                .addGap(18, 18, 18)
                .addComponent(btnManageBookings)
                .addGap(10, 10, 10)
                .addComponent(btnImportXMLData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewCars)
                .addGap(26, 26, 26)
                .addComponent(lblSearchBy)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBrand)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchAvailability)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchManufactureYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchSeats)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchVehicleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchModelNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExpiredCars)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(selectionPanel);

        javax.swing.GroupLayout workPanelLayout = new javax.swing.GroupLayout(workPanel);
        workPanel.setLayout(workPanelLayout);
        workPanelLayout.setHorizontalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        workPanelLayout.setVerticalGroup(
            workPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(workPanel);

        jScrollPane1.setViewportView(jSplitPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCarProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCarProfileActionPerformed
        // TODO add your handling code here:
        CreateCarProfilePanel createCarProfile = new CreateCarProfilePanel(carRecords);
        jSplitPane1.setRightComponent(createCarProfile); 
    }//GEN-LAST:event_btnCreateCarProfileActionPerformed

    private void btnViewCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCarsActionPerformed
        // TODO add your handling code here:
        ViewCarProfilePanel viewCarProfile = new ViewCarProfilePanel(carRecords);
        jSplitPane1.setRightComponent(viewCarProfile);
    }//GEN-LAST:event_btnViewCarsActionPerformed

    private void btnSearchSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchSeatsActionPerformed
        // TODO add your handling code here:
        SearchBySeatsPanel searchBySeats = new SearchBySeatsPanel(carRecords);
        jSplitPane1.setRightComponent(searchBySeats);
    }//GEN-LAST:event_btnSearchSeatsActionPerformed

    private void btnSearchAvailabilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAvailabilityActionPerformed
        // TODO add your handling code here:
        SearchByAvailabilityPanel searchByAvailability = new SearchByAvailabilityPanel(carRecords);
        jSplitPane1.setRightComponent(searchByAvailability);
    }//GEN-LAST:event_btnSearchAvailabilityActionPerformed

    private void btnSearchCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCityActionPerformed
        // TODO add your handling code here:
        SearchByCityPanel searchByCity = new SearchByCityPanel(carRecords);
        jSplitPane1.setRightComponent(searchByCity);
    }//GEN-LAST:event_btnSearchCityActionPerformed

    private void btnSearchManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchManufactureYearActionPerformed
        // TODO add your handling code here:
        SearchByManufactureYear searchByManufactureYear = new SearchByManufactureYear(carRecords);
        jSplitPane1.setRightComponent(searchByManufactureYear);
    }//GEN-LAST:event_btnSearchManufactureYearActionPerformed

    private void btnSearchBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBrandActionPerformed
        // TODO add your handling code here:
        SearchByBrandPanel searchByBrand = new SearchByBrandPanel(carRecords);
        jSplitPane1.setRightComponent(searchByBrand);
    }//GEN-LAST:event_btnSearchBrandActionPerformed

    private void btnSearchVehicleNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchVehicleNumberActionPerformed
        // TODO add your handling code here:
        SearchByVehicleNumberPanel searchByVehicleNumber = new SearchByVehicleNumberPanel(carRecords);
        jSplitPane1.setRightComponent(searchByVehicleNumber);
    }//GEN-LAST:event_btnSearchVehicleNumberActionPerformed

    private void btnManageBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBookingsActionPerformed
        // TODO add your handling code here:
        BookingPanel bookingPanel = new BookingPanel(carRecords);
        jSplitPane1.setRightComponent(bookingPanel);
    }//GEN-LAST:event_btnManageBookingsActionPerformed

    private void btnExpiredCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpiredCarsActionPerformed
        // TODO add your handling code here:
        ExpiredCertificateCarsPanel expiredCertificateCars = new ExpiredCertificateCarsPanel(carRecords);
        jSplitPane1.setRightComponent(expiredCertificateCars);
    }//GEN-LAST:event_btnExpiredCarsActionPerformed

    private void btnImportXMLDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportXMLDataActionPerformed
        // TODO add your handling code here:
        ImportDataFromXML importDataFromXML = new ImportDataFromXML(carRecords);
        jSplitPane1.setRightComponent(importDataFromXML);
    }//GEN-LAST:event_btnImportXMLDataActionPerformed

    private void btnSearchModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchModelNumberActionPerformed
        // TODO add your handling code here:
        SearchByModelNumber searchByModelNumber = new SearchByModelNumber(carRecords);
        jSplitPane1.setRightComponent(searchByModelNumber);
    }//GEN-LAST:event_btnSearchModelNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCarProfile;
    private javax.swing.JButton btnExpiredCars;
    private javax.swing.JButton btnImportXMLData;
    private javax.swing.JButton btnManageBookings;
    private javax.swing.JButton btnSearchAvailability;
    private javax.swing.JButton btnSearchBrand;
    private javax.swing.JButton btnSearchCity;
    private javax.swing.JButton btnSearchManufactureYear;
    private javax.swing.JButton btnSearchModelNumber;
    private javax.swing.JButton btnSearchSeats;
    private javax.swing.JButton btnSearchVehicleNumber;
    private javax.swing.JButton btnViewCars;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblSearchBy;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JPanel workPanel;
    // End of variables declaration//GEN-END:variables
}
