/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import model.AppConstants;
import model.CarProfile;
import model.CarRecords;

/**
 *
 * @author architnigam
 */
public class SearchByBrandPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchByBrandPanel
     */
    CarRecords carRecords;
    AppConstants AppConstants = new AppConstants();
    public SearchByBrandPanel(CarRecords carRecords) {
        initComponents();
        this.carRecords = carRecords;
        populateBrandData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblBrand = new javax.swing.JLabel();
        ddBrand = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrands = new javax.swing.JTable();
        lblNoRecordsFound = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBrandCount = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lblBrand.setText("Brand:");

        ddBrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toyota", "BMW", "Audi", "Chevrolet", "Nissan", "Honda", "Hyundai", "Mercedes", "Ford", "Dodge", "Skoda", "KIA" }));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblBrands.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Car ID", "Driver Name", "Vehicle Number", "Availability", "Location", "Maximum Capacity", "Certificate Expiry"
            }
        ));
        jScrollPane1.setViewportView(tblBrands);

        tblBrandCount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Brand Name", "Number of cars available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblBrandCount);

        jLabel1.setText("Summary of Car Data by Brand: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNoRecordsFound)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBrand)
                                        .addGap(26, 26, 26)
                                        .addComponent(ddBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSearch))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrand)
                    .addComponent(ddBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(5, 5, 5)
                .addComponent(lblNoRecordsFound)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        lblNoRecordsFound.setText("");
        DefaultTableModel model = (DefaultTableModel) tblBrands.getModel();
        model.setRowCount(0);
        String carBrandChosen = ddBrand.getSelectedItem().toString();
        
        for(CarProfile cp : carRecords.getCarRecords())
        {
            if(carBrandChosen.equals(cp.getCarBrand()))
            {
                Object[] row = new Object[6];
                row[0] =  cp.getDriverName();
                row[1] =  cp.getCarBrand() + " " + cp.getCarModelNumber();
                row[2] = cp.getCarSerialNumber();
                row[3] = cp.getAvailabilityStatus();
                row[4] = cp.getCarLoctatedInCity();
                row[5] = cp.getMaximumSeatingCapacity();
                model.addRow(row);
            }
        }
        if(tblBrands.getRowCount() == 0)
        {
            lblNoRecordsFound.setText(AppConstants.NoRecordsFound);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    public enum CarBrands {
    
    Toyota, BMW, Audi, Chevrolet, Nissan, Honda, Hyundai, Mercedes, Ford, Dodge, Skoda, KIA
    
}

    public void populateBrandData()
    {
        String[] cars = {"Toyota", "BMW", "Audi", "Chevrolet", "Nissan", "Honda", "Hyundai", "Mercedes", "Ford", "Dodge", "Skoda", "KIA"};
        ArrayList<String>  carBrandList = new ArrayList<String>();
        ArrayList<String>  frequency = new ArrayList<String>();
        DefaultTableModel model = (DefaultTableModel) tblBrandCount.getModel();
        model.setRowCount(0);
        
        for(CarProfile cp : carRecords.getCarRecords())
        {
            String carBrand = cp.getCarBrand();
            carBrandList.add(carBrand);
        }
         
         
        for (CarBrands day : CarBrands.values()) 
        { 
           int countOfCar = Collections.frequency(carBrandList, day.name());
            String carCount = String.valueOf(countOfCar);
            frequency.add(carCount);
         }
         
        for(int index = 0; index < frequency.size(); index++)
        {
           Object[] row = new Object[2];
           row[0] =  cars[index];
           row[1] =  frequency.get(index);
           model.addRow(row); 
        }
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> ddBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblNoRecordsFound;
    private javax.swing.JTable tblBrandCount;
    private javax.swing.JTable tblBrands;
    // End of variables declaration//GEN-END:variables
}
