/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.util.ArrayList;

/**
 *
 * @author architnigam
 */
public class ResidentRecords {
    private ArrayList<ResidentInfo> residentRecords;
    
    public ResidentRecords()
    {
        this.residentRecords = new ArrayList<ResidentInfo>();
    }

    public ArrayList<ResidentInfo> getResidentRecords() {
        return residentRecords;
    } 

    public void setResidentRecords(ArrayList<ResidentInfo> residentRecords) {
        this.residentRecords = residentRecords;
    }  
    
    public ResidentInfo addResidentRecord()
    {
        ResidentInfo newResident = new ResidentInfo();
        residentRecords.add(newResident);
        return newResident;
    }
    
    public int NumberOfResidentRecords()
    {
        return residentRecords.size();
    }
    
    public int GenerateResidentID()
    {
        int autoGeneratedID = NumberOfResidentRecords();
        return autoGeneratedID + 100;
    }
}
